# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Comment
version: 2.1
# Use a package of configuration called an orb.
#orbs:
  # Security scan orb
  #sast-scan: appthreat/sast-scan@1.3.2
# Orchestrate or schedule a set of jobs
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Compile and prepare volume
          command: |
            # Compile the code
            mvn compile
            # Create a dummy container with the application data
            docker create -v /app --name appcon alpine:3.4 /bin/true
            # Copy the repo to the temporary volume
            docker cp $PWD appcon:/app
      - run:
          name: Perform sast-scan
          command: |
            set +e
            # start an application container using this volume
            docker run --name sastscan -e "WORKSPACE=${CIRCLE_REPOSITORY_URL}" --volumes-from appcon quay.io/appthreat/sast-scan scan --src /app --out_dir /app/reports
            # Copy the reports
            docker cp sastscan:/app/reports reports
      - store_artifacts:
          path: reports
          destination: sast-scan-reports
